language: rust

env:
  global:
    - RUST_BACKTRACE: full

matrix:
  fast_finish: true
  include:
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin
    - os: windows
      rust: stable
      env:
        - EXE_SUFFIX=.exe
        - TARGET=x86_64-pc-windows-msvc

cache: cargo

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

before_deploy:
  - bash ci/before_deploy.sh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: android_localization-*-$TARGET.tar.gz
  skip_cleanup: true
  draft: true
  overwrite: false
  on:
    branch: master
    tags: true

branches:
  only:
    # Pushes and PR to the master & develop branch
    - master
    - develop
    - /^\d+\.\d+\.\d+$/

notifications:
  email:
    on_success: never