[package]
name = "android_strings_cli"
version = "0.1.0"
authors = ["jayrave <jayanthan.raveendiran@gmail.com>"]

[dependencies]
android_strings_core = { path = "../core" }
clap = "2.32.0"
lazy_static = "1.1.0"
regex = "1.0.5"