[package]
name = "android_localization_cli"
version = "0.1.0"
authors = ["jayrave <jayanthan.raveendiran@gmail.com>"]
edition = '2018'

[dependencies]
android_localization_core = { path = "../core" }
clap = "2.32.0"
console = "0.6.2"
lazy_static = "1.1.0"
regex = "1.0.5"